// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArn5kDfyrAdWAJhBqRJqlj7NpnyKIzEOI',
    appId: '1:765114229210:web:0105bb5766c49b9155a0e3',
    messagingSenderId: '765114229210',
    projectId: 'social-network-4b8e8',
    authDomain: 'social-network-4b8e8.firebaseapp.com',
    storageBucket: 'social-network-4b8e8.appspot.com',
    measurementId: 'G-EQX9FVMQRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCakzaHPNCssmFpf14AMCMRMfcN-uITOJU',
    appId: '1:765114229210:android:2c8b38b0eb7d74e755a0e3',
    messagingSenderId: '765114229210',
    projectId: 'social-network-4b8e8',
    storageBucket: 'social-network-4b8e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhSM5zM7KO9EbhOpHPsziOLCmYSqhYqpE',
    appId: '1:765114229210:ios:0050c893a705ddeb55a0e3',
    messagingSenderId: '765114229210',
    projectId: 'social-network-4b8e8',
    storageBucket: 'social-network-4b8e8.appspot.com',
    iosBundleId: 'com.example.familyTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhSM5zM7KO9EbhOpHPsziOLCmYSqhYqpE',
    appId: '1:765114229210:ios:0050c893a705ddeb55a0e3',
    messagingSenderId: '765114229210',
    projectId: 'social-network-4b8e8',
    storageBucket: 'social-network-4b8e8.appspot.com',
    iosBundleId: 'com.example.familyTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArn5kDfyrAdWAJhBqRJqlj7NpnyKIzEOI',
    appId: '1:765114229210:web:9e81dcb68930673855a0e3',
    messagingSenderId: '765114229210',
    projectId: 'social-network-4b8e8',
    authDomain: 'social-network-4b8e8.firebaseapp.com',
    storageBucket: 'social-network-4b8e8.appspot.com',
    measurementId: 'G-H20M3ZC8ME',
  );
}
